### ISSUE TITLE
shinyloadtest should extract worker ID if present

### ISSUE THREAD

**Issue by wch** [rstudio/shinyloadtest#1]
This would give data which would help us to diagnose and debug issues with the utilization scheduler on the server side.

**Comment by wch** [comment]
This has been implemented in rstudio/shinytest@a8a37d8.

**Comment by Mr-Paradox** [comment]
Radix '.tech' Domain: 10-Yr Subscription
$39.99 $250
😃😃😆😭😭😝😝😊😋😋😂😵😖😉😉😁😚😏😏😬😎😎😍😛😨😠😅😘😘😔😔😪☺😀😩😓😓😷😌😤😣😫😥😥😣😑😐😯😰😢😴😈😇😒😞😗😗💞💝💋😙😶😟💘❤💖😧😧💖💙💚💕😕😕😕💟💛💜💔😮😸😸🙀👿🙈😼😼🙉🙈👾🙉😻😻🎅👻💩👺😽😹😹💩💣💥😿😿💨👷👴👷💤💢👳👯💇👨💫💫💇💆👩👼👱👱👦🚿👧👮👮🛁👍👋👏👅👅👅👈👈✌👃✋👇✊👂👀👊☝☝👐💪👬👥🙏🙌👬👭🙇💃🚹🙇💑👪🙎🚺🚺👪👫🙍👫🚼👶🙆🙆🐶🐅🐇🐇🐱🐕🐷🐲🐽🐈🐨🐨🐺🐺🐑🐯🐻🐑🐭🐒🐵🐸🐹🐹🐂🐴🐃🐁🐃🐎🐪🐓🐣🐏🐫🐆🐥🐤🐩🐾🐦🐔🐔🐋🐊🌷🐞🐠🐟🐞🌸🐜🐙🐙🐜🌻🐛🐚🐬🐌💮🌲💐🐢🍃🍅🍎🍀🍀🍏🍐🍊🌱🌱🍌🍈🍑🌿🌾🍍🍍🍉🌵🍒🍝🍣🍝🍄🍠🍥🍔🍚🍔🍱🍴🍟🍛🍤🍳🍗🍙🍨🍫🍹🍫🍧🍭☕🎂🍮🍶🍬🍰🍺🍯🍼🍞🍩🍷🌟💦⚡🌅🌅⛄⛄🌌🌈🌌🌁🌋☁☔🌉🗻🌊🌂🌂☀☀🌎🌐🌝🌔🌐🌕🌚🌜🌖🌖🌜🌗🌛🌘🌙🌏🌑👕👚💼💼👚👗🎓👝💍💍👛🎒👑👖💅👟👞👙👙👠🎏🏮🎐👢👢🎈🎈🎋🎆🎆🎁📦🎃🎇🎉🎑📷🎎🎊🎊📹📟📆📺🎬📠🎫📝✉📱✉📝📜📧☎📃📃💌📞📘📕📂📂📙📙💾💾📗📖📇💿📈📚📔📉📀📼📓🔬💬🎨💬🔨✏⏰⌚🔧🔧✒⌚🔔📌🔎🔎💡🔌🔍🔍🎼🎷💊🎺🎵🎺🎲📯🎧🎧〽🎰📢🎤🎹🀄🃏🎸🎸🔒🔮🔐🏆🔏💰🔏⌛🔑⌛🔫⏳🔪🚬🔱🚙🚐🚝🚐🚗🚘🚛🚆🚆🚕🚖🚚🚞🚋🚑🚔🚓🚟🚎🚂🚌🚃✈🚴🚅🚅🚀🚥🚤🚇🚇🚦🚏⛵🚠🅿⚓Ⓜ🚨🚨💺💒🏰🏫⛽⛽🏫🏧⛪🏩🏩⛪🚪🏢🏨🏣🏥⛲🏭🏡🎪⚾🏇♨♨⚽🏂🏉🗽🗽🏉🎿🏀🗿🎡🎾🏊⛳🎢🎳󾓨🗾🎱󾓭󾓮󾓦󾓮󾓬󾓩󾓬󾓪💵󾓪💶󾓫💷󾓥💷❓➕❇✖❕✖✴➗❗⁉✔⭐✅⭕☑🔅❎💲💲▫🔹⚫🔶◽🔶🔵💠◻◻🔯➰◼◼🔳🔳⃣➿⬛⬇⤵▶↔⬅⬅⏩⏪➡↘⏫⏫🔻↖🔻https://github.com/rstudio/shinyloadtest/issues/1⏬https://github.com/rstudio/shinyloadtest/issues/1https://github.com/rstudio/shinyloadtest/issues/1https://github.com/rstudio/shinyloadtest/issues/1🔼↙↗🔽🚷🚭🔕🚽📵🚫📵🚩🚮📳⚠⚠📴🚮🚯🔇♿🔈🚱🔉🇦🇧🇷🇸🇰🇨🇨🇹🇹🇲🇪🇪🇪🇲🇻🇳🇫🇬🇴🇼🇽🇵🇭🇾🇾🔚🆒🔛🔠🔠🆓🆔🔜🔡🔤🔤🆕🆖ℹ🔢🔣🆙🆗🆘🔟🔟🉑🉑🈂🈂🈴🈯🈵💳💳🈶㊙㊙🈶💹🔰🈚㊗🉐🈷💱💸🈸🈸🕛🕧🕟🕣🕣🕟🕐🕐🕔🕤🕙🕕🕑🕑🕕🕕🕙🕦🕡🕝🕝🕡🕚🕚🕢🕞🅰🅱📪♉♉🅱🅾📬♋♌📭♠♠📨♍📩♥♣📥♎📤♦♦♑↪♒↩♒🔀⛎♐🛅♑↪♓🔀⛎🔁🛂🔂🛃🔃🔃🔃🛄🔄(*^ô^*)ψ(｀∇´)ψlhttps://github.chttps://github.com/rstudio/shinyloadtest/issueshttps://github.com/rstudio/shinyloadtest/issues/1/1om/rstudio/shinyloadtest/issues/1https://github.com/rstudio/shinyloadtest/issues/1https://github.com/rstudio/shinyloadtest/issues/https://github.com/rstudio/shinyloadtest/issues/11

**Comment by slopp** [comment]
I flagged a previous comment as abuse and removed it from this thread.
