### ISSUE TITLE
no support for google analytics?

### ISSUE THREAD

**Issue by joeramirez** [rstudio/shinyloadtest#128]
Hi,  does shinyloadtest not support google analytics?  When I set X workers to test, I don't see any of them register on my google analytics overview, nor do I see any of the associated events.  I imagine since this isn't really using a real browser that these won't be registered by google but I just want to confirm that is true.  If so, is there any future support for GA?

**Comment by schloerke** [comment]
When replaying with `shinycannon`, no browsers are launched. Instead, the _actions_ of fake browsers are replayed to the server. 

So, there is no support for GA as no browsers are launched.
