### ISSUE TITLE
Maintainer email address disabled

### ISSUE THREAD

**Issue by jeroen** [rstudio/shinyloadtest#134]
Tried to send an email to the maintainer but I got: 

> Your message wasn't delivered to alan@rstudio.com because the address couldn't be found, or is unable to receive mail.

**Comment by hadley** [comment]
I think @schloerke is probably the maintainer now

**Comment by schloerke** [comment]
Fixed in #139 - https://github.com/rstudio/shinyloadtest/pull/139/commits/2d3d6438ffc8119f7efac7db9a14dc3a3bb61801
