### ISSUE TITLE
Feature request: Support shinyapps.io

### ISSUE THREAD

**Issue by jzadra** [rstudio/shinyloadtest#166]
Not being able to test apps deployed on shinyapps.io is a major shortcoming.  I'm sure if there was an easy solution, that functinoality would exist, but count this as a request for that functionality.  As far as I know, there is no other way to test on shinyapps.io.  This is a critical need to examine how the settings affect a heavy user load.

**Comment by schloerke** [comment]
I agree. It would be **very nice** to load test apps hosted on shinyapps.io

However, shinyapps.io uses SockJS, which is not supported.

Closing as there are no plans to address this.
