### ISSUE TITLE
(documentation issue?) setup & run shinycannon on windows

### ISSUE THREAD

**Issue by kmcd39** [rstudio/shinyloadtest#167]
Hi!

I'm using shinyloadtest and shinycannon to develop and hopefully speed up a shiny app i'm working on.

I'm fairly new to setting up java libraries and documentation seemed to be missing something for me, as a windows 11 user.

The guides i'm using are on [shinyloadtest](https://rstudio.github.io/shinyloadtest/) & [installing shinycannon](https://rstudio.github.io/shinyloadtest/articles/shinycannon.html). 

I installed Java on my system, but the command in the former guide wouldn't work:
```
shinycannon recording.log https://shinyapp.example.com/ --workers 5 --loaded-duration-minutes 2 --output-dir run1
```
gave the error:
```
'shinycannon' is not recognized as an internal or external command,
operable program or batch file.
```

The installation guide tipped me to replace `shinycannon` with `java -jar shinycannon-1.1.3-dd43f6b.jar`. So the modified command: 
```
java -jar shinycannon-1.1.3-dd43f6b.jar recording.log https://shinyapp.example.com/ --workers 5 --loaded-duration-minutes 5 --output-dir run1
```
_did_ work. It'd be useful to link to an explainer on how to get the first command (with just "shinycannon") to work.

**Comment by ppm1337** [comment]
It is already explained in the documentation that you've linked:

> Download [shinycannon-1.1.3-dd43f6b.jar](https://github.com/rstudio/shinycannon/releases/download/v1.1.3/shinycannon-1.1.3-dd43f6b.jar) *to the directory you wish to run it in*

(emphasis mine)

If you want to run shinycannon from _any_ directory, you need to add the directory containing the jar file to the PATH.

**Comment by jcheng5** [comment]
Oh
