### ISSUE TITLE
Shiny app with server rendered DT table

### ISSUE THREAD

**Issue by artiom33** [rstudio/shinyloadtest#20]
Hi,

I really liked the idea of this package and I wanted to try it on my app. However it seems like it is failing on loading server-rendered DT tables (it loads non server rendered fine). 

Is it because of the reactivity of tables? Would it be hard to fix it? Is it something that was planned to be fixed at some point?

Example app:
```
library(shiny)
library(DT)

ui = shinyUI(fluidPage(
  title = 'Use the DT package in shiny',
  h1('A Table Using Client-side Processing'),
  fluidRow(
    column(2),
    column(8, DT::dataTableOutput('tbl_a')),
    column(2)
  ),
  h1('A Table Using Server-side Processing'),
  fluidRow(
    column(2),
    column(8, DT::dataTableOutput('tbl_b')),
    column(2)
  )
))

server = shinyServer(function(input, output, session) {
  output$tbl_a = DT::renderDataTable(iris, server = FALSE)
  output$tbl_b = DT::renderDataTable(iris)
})

shinyApp(ui = ui, server = server)

````

Thanks,

Artiom

**Comment by alandipert** [comment]
Hi @artiom33 thanks for the reports. We intended to support DT and this has been fixed. We'll share more information, and shinycannon, next week.

**Comment by alandipert** [comment]
We released new documentation and now improved our documentation: https://rstudio.github.io/shinyloadtest/

DT is fully supported, so you shouldn't have this problem anymore. If using the latest software you find you still run into this, please re-open.
