### ISSUE TITLE
Long labels obscure event waterfall plot

### ISSUE THREAD

**Issue by alandipert** [rstudio/shinyloadtest#37]
Labels can get very long and obscure event waterfall plots. For an example, see the 2nd plot here: https://rstudio.github.io/shinyloadtest/articles/analyzing-load-test-logs.html#event-waterfall

Perhaps we should truncate labels after a certain length?

**Comment by schloerke** [comment]
have implemented 100 char max

**Comment by schloerke** [comment]
fixed in #40
