### ISSUE TITLE
Clarify system dependency requirements (openssl)

### ISSUE THREAD

**Issue by rpodcast** [rstudio/shinyloadtest#51]
After viewing Alan's excellent [webinar](https://resources.rstudio.com/webinars/load-testing-shiny-alan-dipert) I promptly went to install `shinyloadtest` on my personal dev machine running Ubuntu 18.04.  At first the install failed due to the [`websocket`](https://github.com/rstudio/websocket) package failing to install.  The error messages were rather cryptic about openssl libraries missing.  I see that the [description](https://github.com/rstudio/websocket/blob/master/DESCRIPTION) file mentions `OpenSSL >= 1.0.1` which I already had on my system, but I was missing the development libraries.  After some googling I stumbled upon this [serverfault post](https://serverfault.com/a/929084) and found I needed the `libssl1.0-dev` package.  It would be helpful if the documentation for `shinyloadtest` mentioned this requirement so users can make sure all the prerequisites are installed first.

**Comment by alandipert** [comment]
Thank you @thercast, I also think adding that to the documentation is a good idea.

**Comment by ajwtech** [comment]
Issue #70 is related to this
