### ISSUE TITLE
'Sessions' Image of  'Analyzing Load Test Logs' page is different

### ISSUE THREAD

**Issue by okiyuki99** [rstudio/shinyloadtest#78]
I checked 'Analyzing Load Test Logs' page for deeply understanding insights obtained from analysis report : https://rstudio.github.io/shinyloadtest/articles/analyzing-load-test-logs.html

'Sessions' show the following image:  
![image](https://user-images.githubusercontent.com/1721212/55482801-41111b00-5660-11e9-962b-df842588df8c.png)

However, is the following image correct ? 
![image](https://user-images.githubusercontent.com/1721212/55482923-7cabe500-5660-11e9-9207-e340364a7b03.png)

**Comment by schloerke** [comment]
@okiyuki99 Correct.  Thank you!
